### ISSUE TITLE
p2p: implement dandelion for transaction broadcast

### ISSUE THREAD

**Issue by aguycalled** [nav-io/navio-core#17]
Implement Dandelion++ for transaction broadcast.

### References

[BIP-0156](https://github.com/bitcoin/bips/blob/master/bip-0156.mediawiki)
[Research paper](https://arxiv.org/abs/1805.11060)
[Old codebase pull request](https://github.com/navcoin/navcoin-core/pull/588)

**Comment by aguycalled** [comment]
### More references

[DigiByte implementation on a more recent Bitcoin Core fork](https://github.com/digibyte/digibyte/pulls?q=is%3Apr+dandelion)

**Comment by foxhlchen** [comment]
Hi, I'm a newbie here. I'd like to help implement this. But I have some questions (that might sound stupid :D ) regarding to this: 
1. Why Dandelion proposal has been rejected in bitcoin?? I couldn't find useful explanation.
2. Why we still implement this on navcoin when taking those objection arguments from bitcoin side into consideration??

**Comment by aguycalled** [comment]
Some bitcoin-core developers are against it because of concerns of possible DoS attacks, and their roadmap is clear towards not enhancing the network privacy if there is a higher than 0 chance of introducing a theoretical attack vector.

Monero, which is in the eyes of a few actors with potential motivation to attack their network, has been using it for some time already, with no evidence of being used to attack the network.

https://monero.stackexchange.com/questions/12599/could-recent-dos-attacks-be-avoided-if-dandelion-was-not-implemented

**Comment by foxhlchen** [comment]
> In the existing transaction relay model of Bitcoin Core, transactions that do not make it into a node's mempool -- a proxy for what we expect to be (eventually) mined -- do not get relayed to other nodes.
>
> In the Dandelion protocol, transactions are relayed (in the stem phase) prior to acceptance into a node's mempool. As a result, there are potential DoS vectors if transactions can be systematically relayed via Dandelion but ultimately not be accepted to any node's mempool -- this could either introduce a bandwidth DoS, where the Bitcoin network's bandwidth is used up or wasted relaying ultimately useless data; or a CPU-exhaustion DoS, if expensive-to-validate transactions can be relayed without ultimately being mined. [In general, the only way attackers "pay" for the network's resources they consume when relaying is via the transaction fee in their transactions; if attackers can generate transactions that do not ultimately get mined, then any side effects of the relay -- such as validation cost and bandwidth used -- can be achieved for free since those transaction fees are never actually paid, which typically implies that the network's resources could be utilized entirely (since it would be costless for an attacker to ramp up usage).]

https://bitcoin.stackexchange.com/questions/81503/what-is-the-tradeoff-between-privacy-and-implementation-complexity-of-dandelion/81504#81504

This really makes a lot of sense to me. Thank you, Alex!!

**Comment by singhparshant** [comment]
Is there going to be any difference between the logic of the previous implementation and the one to be implemented here?

**Comment by aguycalled** [comment]
no, the logic is the same

**Comment by mxaddict** [comment]
Dandelion merged from https://github.com/nav-io/navio-core/pull/81
